# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
machine:
  php:
    version: 7.1.3
jobs:
  build-job:
    docker:
      - image: centos:7
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      # install make
      - run: yum -y install make
      # install git
      - run: yum -y install git
      # install php
      - run: yum -y install php-pear php-devel gcc ImageMagick ImageMagick-devel ImageMagick-perl
      # install composer
      - run: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - run: php composer-setup.php --filename=composer
      - run: ./composer install -n --prefer-dist
      # install Imagick
      - run: pecl install imagick
      - run: echo "extension=imagick.so" >> /etc/php.ini
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      # run tests!
      - run: ./vendor/bin/phpunit
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
